# Generated by Django 2.2.4 on 2019-08-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='studentID',
            field=models.IntegerField(default='000000000'),
        ),
    ]
