# Generated by Django 2.2.4 on 2019-09-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190808_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forcePasswordChange',
            field=models.BooleanField(default=True),
        ),
    ]
