# Generated by Django 2.2.4 on 2020-04-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_forcepasswordchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='studentID',
        ),
        migrations.AddField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(3, 'Work Study'), (0, 'Student'), (1, 'Mentor'), (2, 'Master Teacher'), (4, 'Admin')], default=0),
        ),
    ]
