# Generated by Django 2.2.10 on 2020-04-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200405_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(4, 'Admin'), (2, 'Work Study'), (3, 'Master Teacher'), (1, 'Mentor'), (0, 'Student')], default=0),
        ),
    ]
