# Generated by Django 2.2.10 on 2020-05-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200512_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(2, 'Work Study'), (3, 'Master Teacher'), (0, 'Student'), (1, 'Mentor'), (4, 'Admin')], default=0),
        ),
    ]
