# Generated by Django 2.2.10 on 2020-05-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200514_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(4, 'Admin'), (0, 'Student'), (2, 'Work Study'), (1, 'Mentor'), (3, 'Master Teacher')], default=0),
        ),
    ]
