# Generated by Django 2.2.10 on 2020-05-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200518_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(4, 'Admin'), (0, 'Student'), (1, 'Mentor'), (2, 'Work Study'), (3, 'Master Teacher')], default=0),
        ),
    ]
