# Generated by Django 2.2.10 on 2020-05-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200518_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(1, 'Mentor'), (0, 'Student'), (4, 'Admin'), (3, 'Master Teacher'), (2, 'Work Study')], default=0),
        ),
    ]
