# Generated by Django 2.2.10 on 2020-05-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200523_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(2, 'Work Study'), (3, 'Master Teacher'), (4, 'Admin'), (0, 'Student'), (1, 'Mentor')], default=0),
        ),
    ]
