# Generated by Django 2.2.10 on 2020-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200527_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Mentor'), (2, 'Work Study'), (3, 'Master Teacher'), (4, 'Admin')], default=0),
        ),
    ]
