# Generated by Django 2.2.10 on 2020-05-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200527_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(0, 'Student'), (3, 'Master Teacher'), (4, 'Admin'), (2, 'Work Study'), (1, 'Mentor')], default=0),
        ),
    ]
