# Generated by Django 2.2.10 on 2020-05-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200527_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(1, 'Mentor'), (3, 'Master Teacher'), (0, 'Student'), (2, 'Work Study'), (4, 'Admin')], default=0),
        ),
    ]
