# Generated by Django 2.2.10 on 2020-05-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200527_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(4, 'Admin'), (3, 'Master Teacher'), (1, 'Mentor'), (2, 'Work Study'), (0, 'Student')], default=0),
        ),
    ]
