# Generated by Django 2.2.10 on 2020-05-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200527_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(4, 'Admin'), (1, 'Mentor'), (3, 'Master Teacher'), (0, 'Student'), (2, 'Work Study')], default=0),
        ),
    ]
