# Generated by Django 2.2.10 on 2020-05-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200527_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(2, 'Work Study'), (4, 'Admin'), (0, 'Student'), (1, 'Mentor'), (3, 'Master Teacher')], default=0),
        ),
    ]
