# Generated by Django 2.2.10 on 2020-06-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200602_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(2, 'Work Study'), (1, 'Mentor'), (3, 'Master Teacher'), (0, 'Student'), (4, 'Admin')], default=0),
        ),
    ]
