# Generated by Django 2.2.10 on 2020-06-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200602_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(1, 'Mentor'), (2, 'Work Study'), (4, 'Admin'), (0, 'Student'), (3, 'Master Teacher')], default=0),
        ),
    ]
