# Generated by Django 2.2.10 on 2020-06-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200602_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(4, 'Admin'), (0, 'Student'), (1, 'Mentor'), (3, 'Master Teacher'), (2, 'Work Study')], default=0),
        ),
    ]
