# Generated by Django 2.2.10 on 2020-06-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20200604_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Mentor'), (2, 'Work Study'), (4, 'Admin'), (3, 'Master Teacher')], default=0),
        ),
    ]
