# Generated by Django 2.2.10 on 2020-06-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20200626_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='classification',
            field=models.IntegerField(choices=[(0, 'Student'), (3, 'Master Teacher'), (4, 'Admin'), (1, 'Mentor'), (2, 'Work Study')], default=0),
        ),
    ]
