# Generated by Django 2.2.10 on 2020-04-14 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('MATH', 'Mathematics'), ('CHEM', 'Chemistry'), ('BIO', 'Biology'), ('HOUSE', 'Household'), ('CRAFT', 'Craft'), ('PHYS', 'Physics'), ('TOY', 'Toy'), ('TECH', 'Tech')], max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(7, 'RETURNED'), (8, 'EMPTIED'), (1, 'STARTED'), (3, 'UPDATED'), (5, 'SELF-FILLED'), (4, 'FILLED'), (2, 'PLACED'), (6, 'OUT'), (9, 'DONE'), (0, 'ASSIGNED')], default=0)),
                ('trello_id', models.CharField(blank=True, max_length=50)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('lesson_date', models.DateField(blank=True, null=True)),
                ('lesson_start_time', models.TimeField(blank=True, null=True)),
                ('lesson_end_time', models.TimeField(blank=True, null=True)),
                ('other_notes', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.Course')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Order')),
                ('order_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Course')),
                ('course_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
