# Generated by Django 2.2.10 on 2020-04-15 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(6, 'OUT'), (2, 'PLACED'), (5, 'SELF-FILLED'), (8, 'EMPTIED'), (7, 'RETURNED'), (1, 'STARTED'), (4, 'FILLED'), (9, 'DONE'), (0, 'ASSIGNED'), (3, 'UPDATED')], default=0),
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('other_notes', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('self_filled', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Order')),
            ],
        ),
    ]
