# Generated by Django 2.2.10 on 2020-05-18 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0004_auto_20200514_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='master_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'UPDATED'), (5, 'SELF-FILLED'), (8, 'EMPTIED'), (0, 'ASSIGNED'), (6, 'OUT'), (2, 'PLACED'), (9, 'DONE'), (7, 'RETURNED'), (4, 'FILLED'), (1, 'STARTED')], default=0),
        ),
    ]
