# Generated by Django 2.2.10 on 2020-05-18 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_auto_20200518_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'UPDATED'), (4, 'FILLED'), (5, 'SELF-FILLED'), (9, 'DONE'), (0, 'ASSIGNED'), (1, 'STARTED'), (7, 'RETURNED'), (8, 'EMPTIED'), (6, 'OUT'), (2, 'PLACED')], default=0),
        ),
    ]
