# Generated by Django 2.2.10 on 2020-05-18 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20200518_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(4, 'FILLED'), (1, 'STARTED'), (5, 'SELF-FILLED'), (3, 'UPDATED'), (8, 'EMPTIED'), (9, 'DONE'), (7, 'RETURNED'), (6, 'OUT'), (2, 'PLACED'), (0, 'ASSIGNED')], default=0),
        ),
    ]
