# Generated by Django 2.2.10 on 2020-05-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_auto_20200518_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'STARTED'), (4, 'FILLED'), (0, 'ASSIGNED'), (7, 'RETURNED'), (8, 'EMPTIED'), (5, 'SELF-FILLED'), (6, 'OUT'), (3, 'UPDATED'), (2, 'PLACED'), (9, 'DONE')], default=0),
        ),
    ]
