# Generated by Django 2.2.10 on 2020-05-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_auto_20200523_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(7, 'RETURNED'), (1, 'STARTED'), (5, 'SELF-FILLED'), (9, 'DONE'), (4, 'FILLED'), (2, 'PLACED'), (3, 'UPDATED'), (8, 'EMPTIED'), (6, 'OUT'), (0, 'ASSIGNED')], default=0),
        ),
    ]
