# Generated by Django 2.2.10 on 2020-05-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_auto_20200527_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'PLACED'), (9, 'DONE'), (5, 'SELF-FILLED'), (4, 'FILLED'), (1, 'STARTED'), (6, 'OUT'), (3, 'UPDATED'), (8, 'EMPTIED'), (7, 'RETURNED'), (0, 'ASSIGNED')], default=0),
        ),
    ]
