# Generated by Django 2.2.10 on 2020-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_auto_20200527_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(8, 'EMPTIED'), (2, 'PLACED'), (9, 'DONE'), (4, 'FILLED'), (5, 'SELF-FILLED'), (7, 'RETURNED'), (6, 'OUT'), (0, 'ASSIGNED'), (3, 'UPDATED'), (1, 'STARTED')], default=0),
        ),
    ]
