# Generated by Django 2.2.10 on 2020-05-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_auto_20200527_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(6, 'OUT'), (4, 'FILLED'), (8, 'EMPTIED'), (1, 'STARTED'), (3, 'UPDATED'), (9, 'DONE'), (5, 'SELF-FILLED'), (7, 'RETURNED'), (2, 'PLACED'), (0, 'ASSIGNED')], default=0),
        ),
    ]
