# Generated by Django 2.2.10 on 2020-05-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_auto_20200527_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'PLACED'), (1, 'STARTED'), (5, 'SELF-FILLED'), (3, 'UPDATED'), (7, 'RETURNED'), (6, 'OUT'), (4, 'FILLED'), (9, 'DONE'), (8, 'EMPTIED'), (0, 'ASSIGNED')], default=0),
        ),
    ]
