# Generated by Django 2.2.10 on 2020-05-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_auto_20200527_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'STARTED'), (2, 'PLACED'), (7, 'RETURNED'), (0, 'ASSIGNED'), (5, 'SELF-FILLED'), (9, 'DONE'), (6, 'OUT'), (4, 'FILLED'), (8, 'EMPTIED'), (3, 'UPDATED')], default=0),
        ),
    ]
