# Generated by Django 2.2.10 on 2020-05-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_auto_20200527_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'UPDATED'), (8, 'EMPTIED'), (6, 'OUT'), (2, 'PLACED'), (0, 'ASSIGNED'), (7, 'RETURNED'), (9, 'DONE'), (5, 'SELF-FILLED'), (1, 'STARTED'), (4, 'FILLED')], default=0),
        ),
    ]
