# Generated by Django 2.2.10 on 2020-06-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_auto_20200602_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'ASSIGNED'), (8, 'EMPTIED'), (1, 'STARTED'), (6, 'OUT'), (2, 'PLACED'), (3, 'UPDATED'), (7, 'RETURNED'), (4, 'FILLED'), (5, 'SELF-FILLED'), (9, 'DONE')], default=0),
        ),
    ]
