# Generated by Django 2.2.10 on 2020-06-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0023_auto_20200602_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'ASSIGNED'), (4, 'FILLED'), (3, 'UPDATED'), (6, 'OUT'), (7, 'RETURNED'), (9, 'DONE'), (2, 'PLACED'), (1, 'STARTED'), (8, 'EMPTIED'), (5, 'SELF-FILLED')], default=0),
        ),
    ]
