# Generated by Django 2.2.10 on 2020-06-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0024_auto_20200602_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'PLACED'), (8, 'EMPTIED'), (1, 'STARTED'), (4, 'FILLED'), (7, 'RETURNED'), (6, 'OUT'), (5, 'SELF-FILLED'), (3, 'UPDATED'), (9, 'DONE'), (0, 'ASSIGNED')], default=0),
        ),
    ]
