# Generated by Django 2.2.10 on 2020-06-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0024_auto_20200602_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(6, 'OUT'), (1, 'STARTED'), (8, 'EMPTIED'), (2, 'PLACED'), (9, 'DONE'), (3, 'UPDATED'), (7, 'RETURNED'), (4, 'FILLED'), (5, 'SELF-FILLED'), (0, 'ASSIGNED')], default=0),
        ),
    ]
