# Generated by Django 2.2.10 on 2020-06-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0025_auto_20200623_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'STARTED'), (3, 'UPDATED'), (4, 'FILLED'), (8, 'EMPTIED'), (0, 'ASSIGNED'), (5, 'SELF-FILLED'), (9, 'DONE'), (6, 'OUT'), (2, 'PLACED'), (7, 'RETURNED')], default=0),
        ),
    ]
