# Generated by Django 2.2.10 on 2020-06-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0026_auto_20200626_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(7, 'RETURNED'), (0, 'ASSIGNED'), (1, 'STARTED'), (2, 'PLACED'), (8, 'EMPTIED'), (3, 'UPDATED'), (9, 'DONE'), (6, 'OUT'), (5, 'SELF-FILLED'), (4, 'FILLED')], default=0),
        ),
    ]
