# Generated by Django 2.2.10 on 2020-08-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0027_auto_20200626_0443'),
        ('materials', '0026_auto_20200617_2250'),
    ]

    operations = [
    ]
